<?php
echo"<head><link href='stilos.css' rel='stylesheet' type='text/css'></head>";
//echo "<div id='Layer1' style='position:absolute; left:0px; top:0px; width:1000px; height:80px; z-index:1; background-color: #000000; layer-background-color: #000000; border: 1px none #000000;'><img src='imagenes/cab_peque.jpg'>";
//echo "<center><script src='xaramenu.js'></script><script Webstyle4 src='imagenes/menu_inicio_regional.js'></script></center></div>";
echo "<body background='imagenes/fondo_pagina.jpg'>";
//echo "<center><img src='imagenes/cab4.png'><br>";
//echo "<div style='position:absolute; left:0px; top:100px; width:1000px; border: 1px none #000000;'>";
?>