var TREE_ITEMS_ADM = [
	 	['Administracion',0,
			 		['Cargos','navegador_cargos.php'],
					['Categorias','navegador_categorias.php'],
					['Especialidades','navegador_especialidades.php'],
					['Funcionarios','navegador_funcionarios1.php'],
					['Gestiones','navegador_gestiones.php'],
					['Tipos de Baja','navegador_tiposbaja.php'],
					['Inventarios',0,
						['Registro de Almacenes','navegador_almacenes.php'],
						['Registro de Material de Apoyo','navegador_material.php'],
						['Registro de Muestras Medicas','navegador_muestras_medicas.php'],
						['Registro de Tipos de Material de Apoyo','navegador_tiposmaterial.php'],
						['Registro de Tipos de Ingreso','navegador_tiposingreso.php'],
						['Registro de Tipos de Salida','navegador_tipossalida.php'],
					],
					['Lineas','navegador_lineas.php'],
					
					['Medicos',0,
						['Medicos Listado Madre','navegador_medicos1.php'],
						['Busqueda de Medicos','busqueda_medicos.php'],
					],
					['Reportes',0,
						['Boletas de Categorizaci&oacute;n de M&eacute;dicos','rpt_op_boletasCatMed.php'],
						['Boletas de Categorizaci&oacute;n de M&eacute;dicos x Visitador','rpt_op_boletasCatMedvisitador.php'],
						//['Boletas de Visita','rpt_op_boletasVisita.php'],
						['Encuesta Medicos','rpt_op_encuesta.php'],
						['Observaciones en Boletas de Visita','rpt_op_obs_boletasvisita.php'],
					],
					['Territorios','navegador_territorios.php'],
					['Cambio Datos Funcionario','cambio_datos_funcionario.php'],
		],
	 ];

var TREE_ITEMS_OPE = [
	 	['Modulo Operativo',0,
			 		['Ingreso','ingreso_lineas_visitador_detalle.php'],
					['Ruteros',0,
						['Ruteros Maestro','navegador_rutero_maestro.php'],
						['Ruteros Maestro Aprobados x Ciclo','navegador_rutero_maestroAprobado.php'],
						['Rutero Actual','navegador_rutero_actual.php'],
					],
					['Registro de Visita','registrar_visita_medica.php'],
								['Reportes',0,
				['Medicos',0,
					['M&eacute;dicos en Grupos Especiales (R)','rpt_op_central_grupos_especiales.php'],
				],
				['Parrillas',0,
					['Parrillas Promocionales (R)','rpt_op_parrilla_central.php'],
					['Productos de parrilla por Especialidad (R)','rpt_op_parrilla_productoespecialidad.php'],
				],
				['Visitadores',0,
				 	['Cobertura x Ciclo, Visitador y Categoria (R)','rpt_op_central_coberturaCategoria1.php'],
				 	['Contactos Realizados (R)','rpt_op_contactosRealizados.php'],
				 	['Contactos No Realizados (R)','rpt_op_contactosNoRealizados.php'],
				 	['Productos Visitados (R)','rpt_op_productosVisitados.php'],
					['Detalle de M&eacute;dicos en Rutero Maestro (R)','rpt_op_central_detallemedicos.php'],
					['Medicos en Rutero Maestro Resumido x Visitador(R)','rpt_op_medicos_rutero_maestro2.php'],
					['Medicos en Rutero Maestro Resumido x Visitador(R) x zonas','rpt_op_medicos_rutero_maestro1.php'],
					['Medicos en Rutero Maestro Detallado(R)','rpt_op_medicos_rutero_maestro.php'],
					['Frecuencia y Secuencia de Visita(R)','rpt_op_frecuenciaSecuencia.php'],
					['Secuencia de Visita x Medico(R)','rpt_op_SecuenciaMedico.php'],
					['Parrillas de productos para verificacion de distribucion','rptOpParrillaVeriDist.php'],
				 ],
			],

					['Contactos',0,
						['Administrador','contactos_adm_hermes.php'],
						['Supervisor','contactos_sup_hermes.php'],
					],
					['Cambiar Contrasena','cambiar_contrasena_visitador.php'],
					['Devolucion de MM y MA','navegador_devolucion_visitadorCiclo.php'],
					['Categorizaci&oacute;n M&eacute;dica','categorizacion_medica_lista.php'],
					['Solicitud Alta M&eacute;dicos','medicos_solicitados_lista.php'],
					
		],
	 ];

var TREE_ITEMS_CVS = [
	 	['Modulo Consultores CVS',0,
					['Ruteros',0,
						['Ruteros Maestro','navegador_rutero_maestro_cvs.php'],
						['Ruteros Maestro Aprobados x Ciclo','navegador_rutero_maestroAprobado.php'],
						['Rutero Actual','navegador_rutero_actual.php'],
					],
					['Registro de Visita','registrar_visita_medica.php'],
					['Contactos',0,
						['Administrador','contactos_adm_hermes.php'],
						['Supervisor','contactos_sup_hermes.php'],
					],
					['Cambiar Contrasena','cambiar_contrasena_visitador.php'],
					
		],
	 ];

var TREE_ITEMS_SUP = [
	 	['Modulo Gestion Regional',0,
			 		['Bajas',0,
						['Baja de Dias','navegador_bajas_visitas.php'],
						/*['Baja de Medicos','navegador_bajas_medicos.php'],*/
					],
			 		['Ingreso','ingreso_lineas_regional.php'],
			 		['Visitadores', 'navegador_funcionarios_regional.php'],
					['Contactos',0,
						['Administrador','contactos_adm_hermes.php'],
					],
					['Cambiar Contrasena','cambiar_contrasena_regional.php'],

			['Reportes',0,
				['Medicos',0,
					['M&eacute;dicos en Grupos Especiales (R)','rpt_op_central_grupos_especiales.php'],
					['Universo de M&eacute;dicos (R)','rpt_op_central_cant_med_territorio.php'],
					['Medicos en Rutero Maestro (R)','rpt_op_medicos_rutero_maestroNacional.php'],
					['M&eacute;dicos listado general','rpt_op_central_medicos_base_general.php'],
				],
				['Parrillas',0,
					['Parrillas Promocionales (R)','rpt_op_parrilla_central.php'],
					['Parrillas Personalizadas','rptOpParrillaPersonalizada.php'],
					['Productos de parrilla por Especialidad (R)','rpt_op_parrilla_productoespecialidad.php'],
				],
				['Ruteros',0,
				 	['Ruteros Maestros no Aprobados x Ciclo (R)','rpt_op_ruterosNoAprobados.php'],
				],
				['Productos',0,
				 	['Contactos x Producto x Visitador','rpt_op_contactosxproductoxvisitador.php'],
				],
				['Visitadores',0,
				 	['Cobertura x Ciclo, Visitador y Categoria (R)','rpt_op_central_coberturaCategoria1.php'],
				 	['Contactos Realizados (R)','rpt_op_contactosRealizados.php'],
				 	['Contactos No Realizados (R)','rpt_op_contactosNoRealizados.php'],
				 	['Fechas de Registro x Ciclo (R)','rpt_op_fechasRegistro.php'],
				 	['Productos Visitados (R)','rpt_op_productosVisitados.php'],
					['Detalle de M&eacute;dicos en Rutero Maestro (R)','rpt_op_central_detallemedicos.php'],
					['Medicos en Rutero Maestro Resumido x Visitador(R)','rpt_op_medicos_rutero_maestro2.php'],
					['Medicos en Rutero Maestro Resumido x Visitador(R) x zonas','rpt_op_medicos_rutero_maestro1.php'],
					['Medicos en Rutero Maestro Detallado(R)','rpt_op_medicos_rutero_maestro.php'],
					['Frecuencia y Secuencia de Visita(R)','rpt_op_frecuenciaSecuencia.php'],
					['Secuencia de Visita x Medico(R)','rpt_op_SecuenciaMedico.php'],
					['Devolucion de MM y MA x Ciclo(R)','rpt_op_devolucionMMMA.php'],
					['Parrillas de productos para verificacion de distribucion','rptOpParrillaVeriDist.php'],
				 ],
				 ['Distribuci&oacute;n de Material Promocional',0,
				 // 	['Distribuci&oacute;n x Ciclo x Territorio (R)','rpt_op_central_distribucionTerritorio.php'],
					// ['Distribuci&oacute;n x Ciclo x Visitador (R)','rpt_op_central_distribucion.php'],
					['Distribuci&oacute;n x Ciclo x Territorio (R) (Todos)','rpt_op_central_distribucionTerritorio2.php'],
				 	['Distribuci&oacute;n x Ciclo x Territorio (R)','rpt_op_central_distribucionTerritorio.php'],
					['Distribuci&oacute;n x Ciclo x Visitador (R) (Todos)','rpt_op_central_distribucion2.php'],
					['Distribuci&oacute;n x Ciclo x Visitador (R)','rpt_op_central_distribucion.php'],
					// ['Distribuci&oacute;n x Ciclo x Visitador, Linea y Grupos Especiales(R)','rpt_opDistribucionVisitador.php'],
				 	['MM - MA Pendiente de Reposicion x Territorio (R)','rpt_op_central_distribucionfaltanteTerritorio.php'],
				 	['MM - MA Pendiente de Reposicion x Visitador (R)','rpt_op_central_distribucionfaltanteVisitador.php'],
				 ],
				 ['Estadisticos',0,
				 	['Grilla de medicos en Rutero Maestro Ultimo Ciclo Vigente(R)','rpt_op_grilla.php'],
				 	['Grillas x Estado(R)','rpt_op_grillaEstado.php'],
				 	['Baja de Dias(R)','rpt_op_bajaDias.php'],
				 	['Baja de Medicos(R)','rpt_op_bajaMedicos.php'],
				 	['Cobertura de Encuestas x Visitador(R)','rpt_op_central_encuesta.php'],
				 	['Cantidad de Medicos x Zona','rpt_op_medicosDistritoZona.php'],
				 ],
			],
                ['Lista Categorizacion m&eacute;dico','lista_categorizacion_medico_supervisor.php'],

			['Banco de Muestras',0,
				 	['Banco de Muestras Registro M&eacute;dicos','banco_de_muestras.php'], 
				 	['Calcular Banco de Muestras M&eacute;dicos','calculo_banco_muestras.php'],
			],
			['Aprobacion Bajas',0,
            	   ['Aprobar Bajas Medicos','aprobar_bajas_medicos.php'],
			],	
			['Solicitudes para agregar/quitar Productos',0,
            	   ['Solicitudes Para Agregar Productos','solicitud_agregar_productos_pre_supervisor.php'],
            	   ['Solicitudes Para Quitar Productos','solicitud_quitar_productos_pre_supervisor.php'],
			],	
			['Recalculo Grupos Especiales','recalculo_ge.php'],        			
		],
	 ];


var TREE_ITEMS_GERENCIA = [
		['Modulo de Gestion Estrategica',0,
			['Reportes',0,
				['Funcionarios',0,
					['Funcionarios Habilitados','rpt_op_funcionariosHabilitados.php'],
					['Funcionarios en Lineas de Visita','rpt_op_funcionariosLineasVisita.php'],
					['Funcionarios en Lineas de Visita 2','rpt_op_funcionariosLineasVisita2.php'],
				],
				['Medicos',0,
					['Frecuencias','reporte_frecuencias.php'],
					['Frecuencias de Visita','rpt_op_central_frecuencia_visita.php'],
					['Grupos Especiales (R)','rpt_op_central_grupos_especiales.php'],
					['M&eacute;dicos en Grupos Especiales (R)','rpt_op_central_grupos_especiales1.php'],
					['M&eacute;dicos listado general','rpt_op_central_medicos_base_general.php'],
					['M&eacute;dicos x L&iacute;nea','rpt_op_central_medicos_linea.php'],
					['Medicos en Rutero Maestro (R)','rpt_op_medicos_rutero_maestroNacional.php'],
					['Universo de M&eacute;dicos (R)','rpt_op_central_cant_med_territorio.php'],
					['Reporte para Depuracion de Medicos en Lineas de Visita(Medicos de la Linea Vs. Medicos en Rutero Maestro)','rpt_op_central_depuracionmedicos.php'],
					['Cobertura de Medicos Listado Madre Vs. Rutero Maestro','rpt_op_central_coberturalinea.php'],
					['D&iacute;as Programados Visita por M&eacute;dico','rpt_op_dias_programados.php'],
					['Cobertura por M&eacute;dico','rpt_op_cobertura_medico.php'],
					['Alta M&eacute;dicos por fecha','rpt_op_altamedico_fecha.php'],
				],
				['Parrillas',0,
					['Parrillas Promocionales (R)','rpt_op_parrilla_central.php'],
					['Parrillas Personalizadas','rptOpParrillaPersonalizada.php'],
					['Parrillas Especiales','rpt_op_parrilla_especial.php'],
					['Parrillas Especiales Asignacion','parrillas_especiales_asignacion.php'],
					['Parrillas de productos Resumido','rpt_op_parrilla_centralresumen.php'],
					['Productos de parrilla por Especialidad (R)','rpt_op_parrilla_productoespecialidad.php'],
					['Material de Apoyo por Especialidad','rpt_op_parrilla_materialespecialidad.php'],
				],
				['Productos',0,
				 	['Contactos x Producto','reporte_cantidad_contactos_x_producto.php'],
				 	['x L&iacute;neas de Visita','rpt_op_central_prod_lineas_visita.php'],
					['Grilla de Productos x Especialidad','rpt_op_central_prod_especialidad.php'],
					['Grilla','rpt_op_central_grilla.php'],
					['x Visitador',0,
						['Cantidad de MM y MA planificadas','rpt_op_central_prod_visitador.php'],
						['Cantidad de MM y MA visitadas','rpt_op_central_prod_ent_visitador.php'],
						['Saldo MM y MA a fin de ciclo','rpt_op_central_saldo_muestras_visitador.php'],
						['Contactos x Producto x Visitador','rpt_op_contactosxproductoxvisitador.php'],
					],
				 ],
				 ['Ruteros',0,
				 	['Ruteros Maestros no Aprobados x Ciclo (R)','rpt_op_ruterosNoAprobados.php'],
				 ],
				 ['Visitadores',0,
				 	['Cobertura x Ciclo, Visitador y Categoria (R)','rpt_op_central_coberturaCategoria1.php'],
				 	['Contactos Realizados (R)','rpt_op_contactosRealizados.php'],
				 	['Contactos No Realizados (R)','rpt_op_contactosNoRealizados.php'],
				 	['Fechas de Registro x Ciclo (R)','rpt_op_fechasRegistro.php'],
				 	['Productos Visitados (R)','rpt_op_productosVisitados.php'],
				 	['Rutero Maestro Vs. Ejecutado','rpt_op_central_maestro_vs_ejecutado.php'],
				 	['Memorando de Llamada de Atenci&oacute;n','rpt_op_central_memorando_llamadaatencion.php'],
					['Detalle de M&eacute;dicos en Rutero Maestro (R)','rpt_op_central_detallemedicos.php'],
					['Universo de medicos x Visitador','rpt_op_central_universomedicosvisitador.php'],
					['Medicos en Rutero Maestro Resumido x Visitador(R)','rpt_op_medicos_rutero_maestro2.php'],
					['Medicos en Rutero Maestro Resumido x Visitador(R) x zonas','rpt_op_medicos_rutero_maestro1.php'],
					['Medicos en Rutero Maestro Detallado(R)','rpt_op_medicos_rutero_maestro.php'],
					['Rutero Maestro Consolidado','rptOpRuteroConsolidado.php'],
					['Frecuencia y Secuencia de Visita(R)','rpt_op_frecuenciaSecuencia.php'],
					['Secuencia de Visita x Medico(R)','rpt_op_SecuenciaMedico.php'],
					['Devolucion de MM y MA x Ciclo(R)','rpt_op_devolucionMMMA.php'],
					['Parrillas de productos para verificacion de distribucion','rptOpParrillaVeriDist.php'],
					['Productos x Visitador y Categoria','rptOpProdVisitadorCategorias.php'],
					['Cobertura Vs Devolucion x Ciclo','cobertura_x_devolucion.php'],
					['Visitadores x Zonas','visitadores_x_zonas.php'],
				 ],
				 ['Distribuci&oacute;n de Material Promocional',0,
                    ['Verificacion para la Distribucion(R)','rptOpVerificacionDistNormal.php'],
				 	['Distribuci&oacute;n x Ciclo x Territorio (R) (Todos)','rpt_op_central_distribucionTerritorio2.php'],
				 	['Distribuci&oacute;n x Ciclo x Territorio (R)','rpt_op_central_distribucionTerritorio.php'],
					['Distribuci&oacute;n x Ciclo x Visitador (R) (Todos)','rpt_op_central_distribucion2.php'],
					['Distribuci&oacute;n x Ciclo x Visitador (R)','rpt_op_central_distribucion.php'],
				 	// ['Distribuci&oacute;n x Ciclo x Visitador, Linea y Grupos Especiales(R)','rpt_opDistribucionVisitador.php'],
				 	['MM - MA Pendiente de Reposicion x Territorio (R)(Notas)','rpt_op_central_distribucionfaltanteTerritorio.php'],
				 	['MM - MA Pendiente de Reposicion x Visitador (R)(Notas)','rpt_op_central_distribucionfaltanteVisitador.php'],
				 	['MM - MA Pendiente de Reposicion x Territorio (R)(Faltante)','rpt_op_central_distribucionfaltanteTerritorio2.php'],
				 	['MM - MA Pendiente de Reposicion x Visitador (R)(Faltante)','rpt_op_central_distribucionfaltanteVisitador2.php'],

				 ],
				 ['Estadisticos',0,
				 	['Grilla de medicos en Rutero Maestro Ultimo Ciclo Vigente(R)','rpt_op_grilla.php'],
				 	['Grillas x Estado(R)','rpt_op_grillaEstado.php'],
				 	['Baja de Dias(R)','rpt_op_bajaDias.php'],
				 	['Baja de Medicos(R)','rpt_op_bajaMedicos.php'],
				 	['Cantidad de Medicos x Zona','rpt_op_medicosDistritoZona.php'],
					//['Boletas de Visita','rpt_op_boletasVisita.php'],
					['Boletas de Visita Conjunta','rptOpBoletas.php'],
					//['Boletas de Visita GE','rpt_op_boletasVisitaGE.php'],	
					//['Boletas de Visita BM','rpt_op_boletasVisitaBanco.php'],						
					['Categorizacion M&eacute;dico','rpt_op_categorizacionMedico.php'],
					['Categorizacion M&eacute;dico x Visitador','rpt_op_categorizacionMedicoVisitador.php'],
                                                                                             ['Boletas de Categorizaci&oacute;n de M&eacute;dicos x Visitador','rpt_op_boletasCatMedvisitador.php'],
                                                                                             ['Reporte Categorizaci&oacute;n de M&eacute;dicos','rpt_op_categorizacion_sistema.php'],
				 ],
				 ['Encuestas',0,
				 	['Cobertura de Encuestas x Visitador(R)','rpt_op_central_encuesta.php'],
				 	['Cobertura de Encuestas x Visitador 2(R)','rpt_op_central_encuesta1.php'],
				 	['Cobertura de Encuestas x Territorio(R)','rpt_op_central_encuestaTerritorio.php'],
				 	['Cobertura de Encuestas x Territorio 2(R)','rpt_op_central_encuestaTerritorio1.php'],
				 	['Productos mas utilizados segun encuesta Resumen(R)','rpt_opProductosMasUtilizados.php'],
				 	['Productos mas utilizados segun encuesta Resumen 2(R)','rpt_opProductosMasUtilizados1.php'],
				 	['Productos mas utilizados segun encuesta Detallado por Territorio(R)','rpt_opProductosMasUtilizadosTerritorio.php'],
				 	['Productos mas utilizados segun encuesta Detallado por Territorio 2(R)','rpt_opProductosMasUtilizadosTerritorio1.php'],
				 	['Detalle por Producto, Territorio, Especialidad y Categoria(R)','rpt_opProductosTerritorioEspeCat.php'],
				 	['Detalle por Producto, Territorio, Especialidad y Categoria 2(R)','rpt_opProductosTerritorioEspeCat1.php'],
					['Detalle de Medicos x Frecuencia de Uso de Productos','rpt_opMedicosDetalleProductos.php'],
				 ],
				 ['CVS',0,
					['Medicos en Rutero Resumido(R)','cvs_medicos_resumido.php'],
					['Ruteros Funcionarios CVS(R)','cvs_rutero_resumido.php'],
				],
			],
			['Activar Ciclo','navegador_activar_ciclos.php'],
			['Grillas','grilla_lineas.php'],
			['Grupos Especiales','gruposespeciales_lineas.php'],
			['Lineas de Visita','navegador_lineas_visita_ciclo.php'],
			['Duplicar Lineas de un ciclo','registrar_lineas_visita_x_territorio.php'],
			['Guardar Funcionarios x Linea masivo','llenado_lineas_masivo.php'],
			
			['Distribucion de MM y MA','navegador_distribucion_ciclos.php'],
			['Distribucion de MM y MA Grupos Especiales','navegadorDistribucionGruposCiclos.php'],
			['Distribucion de Banco de Muestras','navegadorDistribucionGruposBanco.php'],
			['Envio de Mensajes','navegador_mensajes.php'],
			['Registro de Medicos',0,
						['Medicos Listado Madre','navegador_medicos1.php'],
						['Busqueda de Medicos','busqueda_medicos.php'],
			],

			['Gestion de Medicos',0,
						['Medicos Territorio','medicos_lineas.php'],
						['Anadir Medicos',0,
								['Listado General','medicosCiudadesGeneral.php'],
								['Busqueda','busqueda_medicos_lineas.php'],
								['Añadir Medicos por Busqueda','busquedaMedAnadir.php'],
								
						],
						['Medicos de la Linea',0,
								['Detallado','navegador_medicos_lineas.php'],
								['Cambiar Categorias Medico','busquedaMedCat.php'],
								
								['Resumido',0,
									['Alfabetico','navegador_medicos_lineas_resumen.php'],
									['Especialidad','navegador_medicos_especialidad.php'],
									['Categoria','navegador_medicos_categoria.php'],
								],
						],
					],
			['Modulo de Gestion Regional','inicio_supernt.php'],
			['Verificacion para Distribucion','rpt_op_verificacion_distribucion.php'],
			['Verificacion para la Distribucion Personalizada','rptOpVerificacionPersonalizada.php'],
//                                                        ['Verificacion para Distribucion Grupos Especiales','rptVerificacionDistribucionGE.php'],
			['Verificacion para Distribucion Grupos Especiales','rpt_op_verificacion_distribucion_ge.php'],
			['Solicitudes para Alta de M&eacute;dicos','medicos_solicitados_lista_gerencia.php'],
			['Alta Centro M&eacute;dico','centro_medico_lista.php'],
			['Cargar Fotos Material Apoyo','fotos_materiales_apoyo2.php'],
                                                        
			['Plan de L&iacute;neas','plan_de_lineas_detalle.php'],
			['Productos Objetivo',0,
				['Productos Objetivo','productos_objetivo.php'],
				['Cantidades Productos Objetivo','cantidades_productos_objetivo.php'],
				['Reporte Productos Objetivo x Visitador','reporte_productos_objetivo.php'],
				['Reporte Productos Objetivo x Zonas','reporte_productos_objetivo_x_zona.php'],
                    ],
            ['Banco de Muestras',0,
            	   ['Aprobar Banco de Muestras M&eacute;dicos','calculo_banco_muestras_apro.php'],
            	   ['Reporte Estado (aprobacion) M&eacute;dicos','reporte_estado_medicos_bm.php'],
            	   ['Reporte Cantidades','reporte_cantidades_bm.php'],
			],

			// ['Llenado Parrillas',0,
   //          	   ['Asignacion de productos','asignacion_productos.php'],
   //          	   ['Replicar Asignacion de productos','duplicar_asignacion_productos.php'],
   //          	   ['Vista Previa Asignacion de productos','asignacion_productos_vp.php'],
   //          	   ['Asignacion MM','llenar_parrilla_asignacion_mm.php'],
   //          	   ['Vista Previa Asignacion MM','llenar_parrilla_asignacion_mm_vp.php'],
			// ],
			['Llenado Parrillas CE',0,
            	   //['Cargar Asignacion de Productos','cargar_excel_asignacion_productos.php'],
            	   ['Asignacion de Productos','asignacion_prodcutos_vista_previap.php'],
            	   //['Cargar Asignacion MM','cargar_excel_asignacion_mm.php'],
            	   ['Cargar Cantidades MM','asignacion_mm_vista_previap.php'],
            	   //['Replicar Asignacion MM','duplicar_asignacion_mm.php'],
            	   ['Verificacion cantidades medicos','verificacion_canitdades_medicos.php'],
            	   ['Asignacion Material De Apoyo','asignacion_ma.php'],
            	   // ['Generar Parrilla','filtro_generacion_parrilla.php'],
            	   ['Generar Parrilla','generar_parrilla_automatica_filtro.php'],
            	   ['Reportes',0,
				 	    //['Consolidado de MM (Existencias)','consolidado_mm_existencias.php'],
				 	    //['Reporte Asignacion MM','asignacion_mm_vista_previap2.php'],
				 	    //['Reporte Asignacion MA General','asignacion_ma_vista_previap.php'],
            	   		//['Reporte Asignacion MA','asignacion_ma_vista_previap2.php'],
            	   		['Reporte Consolidado Asignacion MA','consolidado_ma_existencias.php'],
            	   		//['Analisis de productos x especialidad en parrilla','reporte_posiciones_x_producto.php'],
            	   		//['Reporte Parrilla Final','reporte_parrilla_final.php'],
				   ],
			],
			['Ruteros',0,
            	   ['Aprobar Ruteros','aprobar_rutero_conjunto.php'],
            	   ['Rechazar Ruteros','rechazar_rutero_conjunto.php'],
			],
			['Aprobacion Bajas',0,
            	   ['Aprobar Bajas Medicos','aprobar_bajas_medicos_dr.php'],
			],
			['Adicionar/Quitar Productos M&eacute;dico',0,
            	    ['Aprobar/Rechazar Sugeridos',0,
						['Agregados Sugeridos Supervisor','solicitud_agregar_productos_dr.php'],
						['Quitados Sugeridos Supervisor','solicitud_quitar_productos_dr.php'],
					],
            	   ['Adicionar Producto M&eacute;dico','adicionar_producto_medico.php'],
            	   ['Quitar Producto M&eacute;dico','quitar_producto_medico.php'],
            	   ['Productos Quitados/Adicionados x M&eacute;dico','rptOpProductosFiltradosAdi.php'],
			],
		],
	];
	var TREE_ITEMS_DP = [
		['Modulo de Reportes',0,
			['Reportes',0,
				['Funcionarios',0,
					['Funcionarios Habilitados','rpt_op_funcionariosHabilitados.php'],
					['Funcionarios en Lineas de Visita','rpt_op_funcionariosLineasVisita.php'],
				],
				['Medicos',0,
					['Frecuencias de Visita','rpt_op_central_frecuencia_visita.php'],
					['Grupos Especiales (R)','rpt_op_central_grupos_especiales.php'],
					['M&eacute;dicos en Grupos Especiales (R)','rpt_op_central_grupos_especiales1.php'],
					['M&eacute;dicos listado general','rpt_op_central_medicos_base_general.php'],
					['M&eacute;dicos x L&iacute;nea','rpt_op_central_medicos_linea.php'],
					['Medicos en Rutero Maestro (R)','rpt_op_medicos_rutero_maestroNacional.php'],
					['Universo de M&eacute;dicos (R)','rpt_op_central_cant_med_territorio.php'],
					['Reporte para Depuracion de Medicos en Lineas de Visita(Medicos de la Linea Vs. Medicos en Rutero Maestro)','rpt_op_central_depuracionmedicos.php'],
					['Cobertura de Medicos Listado Madre Vs. Rutero Maestro','rpt_op_central_coberturalinea.php'],
					['D&iacute;as Programados Visita por M&eacute;dico','rpt_op_dias_programados.php'],
					['Cobertura por M&eacute;dico','rpt_op_cobertura_medico.php'],
					['Alta M&eacute;dicos por fecha','rpt_op_altamedico_fecha.php'],
				],
				['Parrillas',0,
					['Parrillas Promocionales (R)','rpt_op_parrilla_central.php'],
					['Parrillas Especiales','rpt_op_parrilla_especial.php'],
					['Parrillas Especiales Asignacion','parrillas_especiales_asignacion.php'],
					['Parrillas de productos Resumido','rpt_op_parrilla_centralresumen.php'],
					['Productos de parrilla por Especialidad (R)','rpt_op_parrilla_productoespecialidad.php'],
					['Material de Apoyo por Especialidad','rpt_op_parrilla_materialespecialidad.php'],
				],
				['Productos',0,
				 	['Contactos x Producto','reporte_cantidad_contactos_x_producto.php'],
				 	['x L&iacute;neas de Visita','rpt_op_central_prod_lineas_visita.php'],
					['Grilla de Productos x Especialidad','rpt_op_central_prod_especialidad.php'],
					['Grilla','rpt_op_central_grilla.php'],
					['x Visitador',0,
						['Cantidad de MM y MA planificadas','rpt_op_central_prod_visitador.php'],
						['Cantidad de MM y MA visitadas','rpt_op_central_prod_ent_visitador.php'],
						['Saldo MM y MA a fin de ciclo','rpt_op_central_saldo_muestras_visitador.php'],
						['Contactos x Producto x Visitador','rpt_op_contactosxproductoxvisitador.php'],
					],
				 ],
				 ['Ruteros',0,
				 	['Ruteros Maestros no Aprobados x Ciclo (R)','rpt_op_ruterosNoAprobados.php'],
				 ],
				 ['Visitadores',0,
				 	['Cobertura x Ciclo, Visitador y Categoria (R)','rpt_op_central_coberturaCategoria1.php'],
				 	['Contactos Realizados (R)','rpt_op_contactosRealizados.php'],
				 	['Contactos No Realizados (R)','rpt_op_contactosNoRealizados.php'],
				 	['Fechas de Registro x Ciclo (R)','rpt_op_fechasRegistro.php'],
				 	['Productos Visitados (R)','rpt_op_productosVisitados.php'],
				 	['Rutero Maestro Vs. Ejecutado','rpt_op_central_maestro_vs_ejecutado.php'],
				 	['Memorando de Llamada de Atenci&oacute;n','rpt_op_central_memorando_llamadaatencion.php'],
					['Detalle de M&eacute;dicos en Rutero Maestro (R)','rpt_op_central_detallemedicos.php'],
					['Universo de medicos x Visitador','rpt_op_central_universomedicosvisitador.php'],
					['Medicos en Rutero Maestro Resumido x Visitador(R)','rpt_op_medicos_rutero_maestro2.php'],
					['Medicos en Rutero Maestro Resumido x Visitador(R) x zonas','rpt_op_medicos_rutero_maestro1.php'],
					['Medicos en Rutero Maestro Detallado(R)','rpt_op_medicos_rutero_maestro.php'],
					['Frecuencia y Secuencia de Visita(R)','rpt_op_frecuenciaSecuencia.php'],
					['Secuencia de Visita x Medico(R)','rpt_op_SecuenciaMedico.php'],
					['Devolucion de MM y MA x Ciclo(R)','rpt_op_devolucionMMMA.php'],
					['Parrillas de productos para verificacion de distribucion','rptOpParrillaVeriDist.php'],
					['Productos x Visitador y Categoria','rptOpProdVisitadorCategorias.php'],
					['Cobertura Vs Devolucion x Ciclo','cobertura_x_devolucion.php'],
					['Visitadores x Zonas','visitadores_x_zonas.php'],
				 ],
				 ['Distribuci&oacute;n de Material Promocional',0,
                    ['Verificacion de Distribucion(R)','rptOpVerificacionDistNormal.php'],
				 	['Distribuci&oacute;n x Ciclo x Territorio (R) (Todos)','rpt_op_central_distribucionTerritorio2.php'],
				 	['Distribuci&oacute;n x Ciclo x Territorio (R)','rpt_op_central_distribucionTerritorio.php'],
					['Distribuci&oacute;n x Ciclo x Visitador (R) (Todos)','rpt_op_central_distribucion2.php'],
					['Distribuci&oacute;n x Ciclo x Visitador (R)','rpt_op_central_distribucion.php'],
				 	// ['Distribuci&oacute;n x Ciclo x Visitador, Linea y Grupos Especiales(R)','rpt_opDistribucionVisitador.php'],
				 	['MM - MA Pendiente de Reposicion x Territorio (R)(Notas)','rpt_op_central_distribucionfaltanteTerritorio.php'],
				 	['MM - MA Pendiente de Reposicion x Visitador (R)(Notas)','rpt_op_central_distribucionfaltanteVisitador.php'],
				 	['MM - MA Pendiente de Reposicion x Territorio (R)(Faltante)','rpt_op_central_distribucionfaltanteTerritorio2.php'],
				 	['MM - MA Pendiente de Reposicion x Visitador (R)(Faltante)','rpt_op_central_distribucionfaltanteVisitador2.php'],

				 ],
				 ['Estadisticos',0,
				 	['Grilla de medicos en Rutero Maestro Ultimo Ciclo Vigente(R)','rpt_op_grilla.php'],
				 	['Grillas x Estado(R)','rpt_op_grillaEstado.php'],
				 	['Baja de Dias(R)','rpt_op_bajaDias.php'],
				 	['Baja de Medicos(R)','rpt_op_bajaMedicos.php'],
				 	['Cantidad de Medicos x Zona','rpt_op_medicosDistritoZona.php'],
					//['Boletas de Visita','rpt_op_boletasVisita.php'],
					['Categorizacion M&eacute;dico','rpt_op_categorizacionMedico.php'],
					['Categorizacion M&eacute;dico x Visitador','rpt_op_categorizacionMedicoVisitador.php'],
                    ['Boletas de Categorizaci&oacute;n de M&eacute;dicos x Visitador','rpt_op_boletasCatMedvisitador.php'],
                    ['Reporte Categorizaci&oacute;n de M&eacute;dicos','rpt_op_categorizacion_sistema.php'],
				 ],
				 ['Encuestas',0,
				 	['Cobertura de Encuestas x Visitador(R)','rpt_op_central_encuesta.php'],
				 	['Cobertura de Encuestas x Visitador 2(R)','rpt_op_central_encuesta1.php'],
				 	['Cobertura de Encuestas x Territorio(R)','rpt_op_central_encuestaTerritorio.php'],
				 	['Cobertura de Encuestas x Territorio 2(R)','rpt_op_central_encuestaTerritorio1.php'],
				 	['Productos mas utilizados segun encuesta Resumen(R)','rpt_opProductosMasUtilizados.php'],
				 	['Productos mas utilizados segun encuesta Resumen 2(R)','rpt_opProductosMasUtilizados1.php'],
				 	['Productos mas utilizados segun encuesta Detallado por Territorio(R)','rpt_opProductosMasUtilizadosTerritorio.php'],
				 	['Productos mas utilizados segun encuesta Detallado por Territorio 2(R)','rpt_opProductosMasUtilizadosTerritorio1.php'],
				 	['Detalle por Producto, Territorio, Especialidad y Categoria(R)','rpt_opProductosTerritorioEspeCat.php'],
				 	['Detalle por Producto, Territorio, Especialidad y Categoria 2(R)','rpt_opProductosTerritorioEspeCat1.php'],
					['Detalle de Medicos x Frecuencia de Uso de Productos','rpt_opMedicosDetalleProductos.php'],
				 ],
			],
			['Verificacion para Distribucion','rpt_op_verificacion_distribucion.php'],
            ['Verificacion para Distribucion Grupos Especiales','rpt_op_verificacion_distribucion_ge.php'],
            ['Productos Objetivo',0,
				['Reporte Productos Objetivo x Visitador','reporte_productos_objetivo.php'],
				['Reporte Productos Objetivo x Zonas','reporte_productos_objetivo_x_zona.php'],
                    ],
            ['Banco de Muestras',0,
            	   ['Reporte Estado (aprobacion) M&eacute;dicos','reporte_estado_medicos_bm.php'],
            	   ['Reporte Cantidades','reporte_cantidades_bm.php'],
			],

			['Llenado Parrillas CE',0,
            	   ['Vista Previa','asignacion_prodcutos_vista_previap.php'],
            	   ['Consolidado de MM (Existencias)','consolidado_mm_existencias.php'],
            	   ['Vista Previa MM','asignacion_mm_vista_previap.php'],
	           	   ['Reporte Asignacion MA General','asignacion_ma_vista_previap.php'],
            	   ['Reporte Asignacion MA','asignacion_ma_vista_previap2.php'],
            	   ['Reporte Consolidado Asignacion MA','consolidado_ma_existencias.php'],
            	   ['Analisis de productos x especialidad en parrilla','reporte_posiciones_x_producto.php'],
			],
		],
	];
var TREE_ITEMS_JL = [
		['Modulo de Gestion Central',0,
			['Ingreso','ingreso_lineas.php'],
			['Grupos Especiales','gruposespeciales_lineas.php'],
			['Ciclos','navegador_ciclos.php'],
			['Lineas de Visita','navegador_lineas_visita.php'],
			['Productos x Especialidad','navegador_prod_especialidad.php'],
			['Parrillas',0,
				['Ciclo en Curso',0,
					['Parrilla Promocional','navegador_parrillas_espe.php'],
					['Parrilla Especial','navegador_parrilla_especial.php'],
				],
				['Ciclos Programados',0,
					['Parrilla Promocional','navegador_parrillas_ciclos.php'],
					['Parrilla Especial','navegador_parrillas_especial_ciclos.php'],
				],
				['Replicar Parrilla Especial','replicarParriEspe.php'
				],
			],
			['Cambiar Contrasena','cambiar_contrasena_central.php'],
			
			['Reportes',0,
				['Funcionarios',0,
					['Funcionarios Habilitados','rpt_op_funcionariosHabilitados.php'],
                    ['Funcionarios en Lineas de Visita','rpt_op_funcionariosLineasVisita.php'],
                    ['Funcionarios en Lineas de Visita 2','rpt_op_funcionariosLineasVisita2.php'],
					
				],
				['Medicos',0,
					['Frecuencias de Visita','rpt_op_central_frecuencia_visita.php'],
					['M&eacute;dicos en Grupos Especiales (R)','rpt_op_central_grupos_especiales.php'],
					['M&eacute;dicos listado general','rpt_op_central_medicos_base_general.php'],
					['M&eacute;dicos x L&iacute;nea','rpt_op_central_medicos_linea.php'],
					['Universo de M&eacute;dicos (R)','rpt_op_central_cant_med_territorio.php'],
					['Reporte para Depuracion de Medicos en Lineas de Visita(Medicos de la Linea Vs. Medicos en Rutero Maestro)','rpt_op_central_depuracionmedicos.php'],
					['Cobertura de Medicos Listado Madre Vs. Rutero Maestro','rpt_op_central_coberturalinea.php'],
				],
				['Parrillas',0,
					['Parrillas Promocionales (R)','rpt_op_parrilla_central.php'],
					['Parrillas Personalizadas','rptOpParrillaPersonalizada.php'],
					['Parrillas Especiales','rpt_op_parrilla_especial.php'],
					['Parrillas Especiales Asignacion','parrillas_especiales_asignacion.php'],
					//['Parrillas de productos Resumido','rpt_op_parrilla_centralresumen.php'],
					//['Productos de parrilla por Especialidad (R)','rpt_op_parrilla_productoespecialidad.php'],
					//['Material de Apoyo por Especialidad','rpt_op_parrilla_materialespecialidad.php'],
				],
				['Productos',0,
				 	['x L&iacute;neas de Visita','rpt_op_central_prod_lineas_visita.php'],
					['Grilla de Productos x Especialidad','rpt_op_central_prod_especialidad.php'],
					['Grilla','rpt_op_central_grilla.php'],
					['x Visitador',0,
						['Cantidad de MM y MA planificadas','rpt_op_central_prod_visitador.php'],
						['Cantidad de MM y MA visitadas','rpt_op_central_prod_ent_visitador.php'],
						['Saldo MM y MA a fin de ciclo','rpt_op_central_saldo_muestras_visitador.php'],
						['Contactos x Producto x Visitador','rpt_op_contactosxproductoxvisitador.php'],
					],
				 ],
				 ['Ruteros',0,
				 	['Ruteros Maestros no Aprobados x Ciclo (R)','rpt_op_ruterosNoAprobados.php'],
				 ],
				 ['Visitadores',0,
				 	['Cobertura x Ciclo, Visitador y Categoria (R)','rpt_op_central_coberturaCategoria1.php'],
				 	['Contactos Realizados (R)','rpt_op_contactosRealizados.php'],
				 	['Contactos No Realizados (R)','rpt_op_contactosNoRealizados.php'],
				 	['Fechas de Registro x Ciclo (R)','rpt_op_fechasRegistro.php'],
				 	['Productos Visitados (R)','rpt_op_productosVisitados.php'],
				 	['Rutero Maestro Vs. Ejecutado','rpt_op_central_maestro_vs_ejecutado.php'],
				 	['Memorando de Llamada de Atenci&oacute;n','rpt_op_central_memorando_llamadaatencion.php'],
					['Detalle de M&eacute;dicos en Rutero Maestro (R)','rpt_op_central_detallemedicos.php'],
					['Universo de medicos x Visitador','rpt_op_central_universomedicosvisitador.php'],
					['Medicos en Rutero Maestro Resumido x Visitador(R)','rpt_op_medicos_rutero_maestro2.php'],
					['Medicos en Rutero Maestro Resumido x Visitador(R) x zonas','rpt_op_medicos_rutero_maestro1.php'],
					['Medicos en Rutero Maestro Detallado(R)','rpt_op_medicos_rutero_maestro.php'],
					['Frecuencia y Secuencia de Visita(R)','rpt_op_frecuenciaSecuencia.php'],
					['Secuencia de Visita x Medico(R)','rpt_op_SecuenciaMedico.php'],
					['Devolucion de MM y MA x Ciclo(R)','rpt_op_devolucionMMMA.php'],
					['Parrillas de productos para verificacion de distribucion','rptOpParrillaVeriDist.php'],
				 ],
				 ['Distribuci&oacute;n de Material Promocional',0,
				 // 	['Distribuci&oacute;n x Ciclo x Territorio (R)','rpt_op_central_distribucionTerritorio.php'],
					// ['Distribuci&oacute;n x Ciclo x Visitador (R)','rpt_op_central_distribucion.php'],
					['Distribuci&oacute;n x Ciclo x Territorio (R) (Todos)','rpt_op_central_distribucionTerritorio2.php'],
				 	['Distribuci&oacute;n x Ciclo x Territorio (R)','rpt_op_central_distribucionTerritorio.php'],
					['Distribuci&oacute;n x Ciclo x Visitador (R) (Todos)','rpt_op_central_distribucion2.php'],
					['Distribuci&oacute;n x Ciclo x Visitador (R)','rpt_op_central_distribucion.php'],
				 	// ['Distribuci&oacute;n x Ciclo x Visitador, Linea y Grupos Especiales(R)','rpt_opDistribucionVisitador.php'],
				 	['MM - MA Pendiente de Reposicion x Territorio (R)','rpt_op_central_distribucionfaltanteTerritorio.php'],
				 	['MM - MA Pendiente de Reposicion x Visitador (R)','rpt_op_central_distribucionfaltanteVisitador.php'],

				 ],
				 ['Estadisticos',0,
				 	['Grilla de medicos en Rutero Maestro Ultimo Ciclo Vigente(R)','rpt_op_grilla.php'],
				 	['Grillas x Estado(R)','rpt_op_grillaEstado.php'],
				 	['Baja de Dias(R)','rpt_op_bajaDias.php'],
				 	['Baja de Medicos(R)','rpt_op_bajaMedicos.php'],
				 	['Cantidad de Medicos x Zona','rpt_op_medicosDistritoZona.php'],
					//['Boletas de Visita','rpt_op_boletasVisita.php'],
				 ],
				 ['Encuestas',0,
				 	['Cobertura de Encuestas x Visitador(R)','rpt_op_central_encuesta.php'],
				 	['Cobertura de Encuestas x Territorio(R)','rpt_op_central_encuestaTerritorio.php'],
				 	['Productos mas utilizados segun encuesta Resumen(R)','rpt_opProductosMasUtilizados.php'],
				 	['Productos mas utilizados segun encuesta Detallado por Territorio(R)','rpt_opProductosMasUtilizadosTerritorio.php'],
				 	['Detalle por Producto, Territorio, Especialidad y Categoria(R)','rpt_opProductosTerritorioEspeCat.php'],

				 ],
			],
//                                                      ['Banco de Muestras Registro M&eacute;dicos','banco_de_muestras.php'],  
//                                                      ['Listado Banco de Muestras M&eacute;dicos','banco_de_muestras2.php'],  
//                                                      ['Calcular Banco de Muestras M&eacute;dicos','calculo_banco_muestras.php'],  
                    ['Cargar Fotos Material Apoyo','fotos_materiales_apoyo2.php'],
                    ['Recalculo Grupos Especiales','recalculo_ge.php'],
                    ['Productos Objetivo',0,
                    	['Productos Objetivo','productos_objetivo.php'],
                    	['Cantidades Productos Objetivo','cantidades_productos_objetivo.php'],
	                    ['Reporte Productos Objetivo x Visitador','reporte_productos_objetivo.php'],
	                    ['Reporte Productos Objetivo x Zonas','reporte_productos_objetivo_x_zona.php'],
                    ],
            ['Llenado Parrillas CE',0,
            	   //['Cargar Asignacion de Productos','cargar_excel_asignacion_productos.php'],
            	   ['Asignacion de Productos','asignacion_prodcutos_vista_previap.php'],
            	   //['Cargar Asignacion MM','cargar_excel_asignacion_mm.php'],
            	   ['Cargar Cantidades MM','asignacion_mm_vista_previap.php'],
            	   //['Replicar Asignacion MM','duplicar_asignacion_mm.php'],
            	   ['Verificacion cantidades medicos','verificacion_canitdades_medicos.php'],
            	   ['Asignacion Material De Apoyo','asignacion_ma.php'],
            	   // ['Generar Parrilla','filtro_generacion_parrilla.php'],
            	   //['Generar Parrilla','generar_parrilla_automatica_filtro.php'],
            	   ['Reportes',0,
				 	    //['Consolidado de MM (Existencias)','consolidado_mm_existencias.php'],
				 	    //['Reporte Asignacion MM','asignacion_mm_vista_previap2.php'],
				 	    //['Reporte Asignacion MA General','asignacion_ma_vista_previap.php'],
            	   		//['Reporte Asignacion MA','asignacion_ma_vista_previap2.php'],
            	   		['Reporte Consolidado Asignacion MA','consolidado_ma_existencias.php'],
            	   		//['Analisis de productos x especialidad en parrilla','reporte_posiciones_x_producto.php'],
            	   		//['Reporte Parrilla Final','reporte_parrilla_final.php'],
				   ],
			],
			/*['Llenado Parrillas CE',0,
            	   ['Cargar Asignacion de Productos','cargar_excel_asignacion_productos.php'],
            	   ['Vista Previa','asignacion_prodcutos_vista_previap.php'],
            	   ['Consolidado de MM (Existencias)','consolidado_mm_existencias.php'],
            	   ['Cargar Asignacion MM','cargar_excel_asignacion_mm.php'],
            	   ['Vista Previa MM','asignacion_mm_vista_previap.php'],
            	   ['Replicar Asignacion MM','duplicar_asignacion_mm.php'],
            	   ['Verificacion cantidades medicos','verificacion_canitdades_medicos.php'],
            	   ['Asignacion Material De Apoyo','asignacion_ma.php'],
            	   ['Reporte Asignacion MA General','asignacion_ma_vista_previap.php'],
            	   ['Reporte Asignacion MA','asignacion_ma_vista_previap2.php'],
            	   ['Reporte Consolidado Asignacion MA','consolidado_ma_existencias.php'],
            	   // ['Generar Parrilla','filtro_generacion_parrilla.php'],
            	   ['Analisis de productos x especialidad en parrilla','reporte_posiciones_x_producto.php'],
            	   // ['Generar Parrilla','generar_parrilla_automatica_filtro.php'],
            	   // ['Reporte Parrilla Final','reporte_parrilla_final.php'],
			],*/
                                                      

		],

	];

var TREE_ITEMS_ALMREG = [


	 	['Modulo de Almacenes',0,
			 		['Ingresos',0,
						['Ingreso de MM en Transito','navegador_ingresomuestrastransito.php'],
						['Ingreso de MA en Transito','navegador_ingresomaterialapoyotransito.php'],
						['Ingreso de MM','navegador_ingresomuestras.php'],
						['Ingreso de MA','navegador_ingresomateriales.php'],
					],
			 		['Salidas',0,
						['Salida de MM','navegador_salidamuestras.php'],
						['Salida de MA','navegador_salidamateriales.php'],
					],
					['Devoluciones',0,
						['Devolucion de MM y MA por Ciclo','navegador_devolucion_almacen.php'],
					],
			 		['Reportes',0,
						['Kardex de Movimiento','rpt_op_inv_kardex.php'],
						['Existencias','rpt_op_inv_existencias.php'],
						['Ingresos','rpt_op_inv_ingresos.php'],
						['Salidas','rpt_op_inv_salidas.php'],
						['Salida de Productos x Regional','rpt_op_inv_salidasRegional.php'],
					],
		],
	 ];
var TREE_ITEMS_ALMREGCON = [
	 	['Modulo de Almacenes',0,
			 	['Reportes',0,
					['Kardex de Movimiento','rpt_op_inv_kardex.php'],
					['Existencias','rpt_op_inv_existencias.php'],
					['Ingresos','rpt_op_inv_ingresos.php'],
					['Salidas','rpt_op_inv_salidas.php'],
					['Salida de Productos x Regional','rpt_op_inv_salidasRegional.php'],
					['Cantidad de MM y MA visitadas','rpt_op_central_prod_ent_visitador.php'],
				],
		],
	 ];

var TREE_ITEMS_LOGIS = [
	 	['Modulo de Inventarios Logistica',0,
			 		['Reportes',0,
						['Kardex de Movimiento','rpt_op_inv_kardex.php'],
						['Existencias','rpt_op_inv_existencias.php'],
						['Stocks','rpt_op_stocks.php'],
						['Ingresos','rpt_op_inv_ingresos.php'],
						['Salidas','rpt_op_inv_salidas.php'],
						['Salida de Productos x Regional','rpt_op_inv_salidasRegional.php'],
					],
					['Cargado de Stocks','cargadoStockMuestras.php'],
		],
	 ];

var TREE_ITEMS_ALMC = [
	 	['Modulo de Almacenes Central',0,
			 		['Ingresos',0,
						['Ingreso de MM',0,
							['Busqueda','navegador_ingresobusqueda.php?grupo_ingreso=1'],
							['Listado General','navegador_ingresomuestras.php'],
                                                                                                                              ['Ingreso de MM en Transito','navegador_ingresomuestrastransito.php'],
						],
						['Ingreso de MA',0,
							['Busqueda','navegador_ingresobusqueda.php?grupo_ingreso=2'],
							['Listado General','navegador_ingresomateriales.php'],
                                                                                                                              ['Ingreso de MA en Transito','navegador_ingresomaterialapoyotransito.php'],
						],
					],
			 		['Salidas',0,
						['Salida de MM',0,
							['Busqueda','navegador_salidabusqueda.php?grupo_salida=1'],
							['Listado General','navegador_salidamuestras.php'],
						],
						['Salida de MA',0,
							['Busqueda','navegador_salidabusqueda.php?grupo_salida=2'],
							['Listado General','navegador_salidamateriales.php'],
						]
					],
			 		['Reportes',0,
			 			['Inventarios',0,
			 				['Kardex de Movimiento','rpt_op_inv_kardex.php'],
							['Existencias','rpt_op_inv_existencias.php'],
							['Ingresos','rpt_op_inv_ingresos.php'],
							['Salidas','rpt_op_inv_salidas.php'],
							['Stocks','rpt_op_stocks.php'],
							['Salida de Productos x Regional','rpt_op_inv_salidasRegional.php'],
							['Cantidad de MM y MA visitadas','rpt_op_central_prod_ent_visitador.php'],
			 			],
					],
                                                                                             ['Generar datos Material Apoyo (BACO)','rpt_op_material_apoyo.php'],
                                                                                             ['Cargar datos Material Apoyo (BACO)','rpt_op_carga_material_apoyo.php'],
                                                                                             // ['Generar datos Muestras M&eacute;dicas (ZEUS)','rpt_op_muestras_medicas.php'],
                                                                                             // ['Cargar datos Muestras M&eacute;dicas (ZEUS)','rpt_op_carga_muestras_medicas.php'],
                                                                                             ['Llenado materiales faltante (Baco)','cargado_Materiales_Baco.php'],
                                                                                             ['Cargar Fotos Material Apoyo','fotos_materiales_apoyo2.php'],
                                                                                             ['Generar Demanda MM','demanda_mm.php'],
                                                                                             ['Demanda MM','demanda_mm_detalle.php'],
		],
	 ];
var TREE_ITEMS_SUPER = [
		['Modulo General HERMES',0,
			['Reportes',0,
				['Medicos',0,
					['Frecuencias de Visita','rpt_op_central_frecuencia_visita.php'],
					['M&eacute;dicos en Grupos Especiales (R)','rpt_op_central_grupos_especiales.php'],
					['M&eacute;dicos listado general','rpt_op_central_medicos_base_general.php'],
					['M&eacute;dicos x L&iacute;nea','rpt_op_central_medicos_linea.php'],
					['Universo de M&eacute;dicos (R)','rpt_op_central_cant_med_territorio.php'],
					['Reporte para Depuracion de Medicos en Lineas de Visita(Medicos de la Linea Vs. Medicos en Rutero Maestro)','rpt_op_central_depuracionmedicos.php'],
					['Cobertura de Medicos Listado Madre Vs. Rutero Maestro','rpt_op_central_coberturalinea.php'],
				],
				['Parrillas',0,
					['Parrillas Promocionales (R)','rpt_op_parrilla_central.php'],
					['Parrillas Especiales','rpt_op_parrilla_especial.php'],
					['Parrillas Especiales Asignacion','parrillas_especiales_asignacion.php'],
					['Parrillas de productos Resumido','rpt_op_parrilla_centralresumen.php'],
					['Productos de parrilla por Especialidad (R)','rpt_op_parrilla_productoespecialidad.php'],
					['Material de Apoyo por Especialidad','rpt_op_parrilla_materialespecialidad.php'],
				],
				['Productos',0,
				 	['x L&iacute;neas de Visita','rpt_op_central_prod_lineas_visita.php'],
					['Grilla de Productos x Especialidad','rpt_op_central_prod_especialidad.php'],
					['Grilla','rpt_op_central_grilla.php'],
					['x Visitador',0,
						['Cantidad de MM y MA planificadas','rpt_op_central_prod_visitador.php'],
						['Cantidad de MM y MA visitadas','rpt_op_central_prod_ent_visitador.php'],
						['Saldo MM y MA a fin de ciclo','rpt_op_central_saldo_muestras_visitador.php'],
						['Contactos x Producto x Visitador','rpt_op_contactosxproductoxvisitador.php'],
					],
				 ],
				 ['Ruteros',0,
				 	['Ruteros Maestros Aprobados x Visitador (R)','rpt_op_ruterosMaestros.php'],
				 ],
				 ['Visitadores',0,
				 	['Cobertura x Ciclo y Visitador (R)','rpt_op_central_cobertura.php'],
				 	['Cobertura x Ciclo, Visitador y Categoria (R)','rpt_op_central_coberturaCategoria.php'],
				 	['Contactos Realizados (R)','rpt_op_contactosRealizados.php'],
				 	['Contactos Rezagados','rpt_op_central_contactos_rezagados.php'],
				 	['Rutero Maestro Vs. Ejecutado','rpt_op_central_maestro_vs_ejecutado.php'],
				 	['Memorando de Llamada de Atenci&oacute;n','rpt_op_central_memorando_llamadaatencion.php'],
					['Detalle de M&eacute;dicos en Rutero Maestro (R)','rpt_op_central_detallemedicos.php'],
					['Universo de medicos x Visitador','rpt_op_central_universomedicosvisitador.php'],
					['Medicos en Rutero Maestro Resumido x Visitador(R)','rpt_op_medicos_rutero_maestro2.php'],
					['Medicos en Rutero Maestro Resumido x Visitador(R) x zonas','rpt_op_medicos_rutero_maestro1.php'],
					['Medicos en Rutero Maestro Detallado(R)','rpt_op_medicos_rutero_maestro.php'],
				 ],
				 ['Distribuci&oacute;n de Material Promocional',0,
				 	['Distribuci&oacute;n x Ciclo x Territorio (R)','rpt_op_central_distribucionTerritorio.php'],
					['Distribuci&oacute;n x Ciclo x Visitador (R)','rpt_op_central_distribucion.php'],
				 	['MM - MA No Distribuido x Ciclo y Territorio (R)','rpt_op_central_distribucionfaltanteTerritorio.php'],
				 	['MM - MA No Distribuido x Ciclo y Visitador (R)','rpt_op_central_distribucionfaltanteVisitador.php'],
				 ],
			],
			['Activar Ciclo','navegador_activar_ciclos.php'],
			['Grillas','grilla_lineas.php'],
			['Grupos Especiales','gruposespeciales_lineas.php'],
			['Distribucion de MM y MA','navegador_distribucion_ciclos.php'],
			['Medicos',0,
						['Medicos Territorio','medicos_lineas.php'],
						['Anadir Medicos',0,
								['Listado General','anadir_medico_linea_general.php'],
								['Busqueda','busqueda_medicos_lineas.php'],
						],
						['Medicos de la Linea',0,
								['Detallado','navegador_medicos_lineas.php'],
								['Resumido',0,
									['Alfabetico','navegador_medicos_lineas_resumen.php'],
									['Especialidad','navegador_medicos_especialidad.php'],
									['Categoria','navegador_medicos_categoria.php'],
								],
						],
					],
			['Modulo de Gestion Regional','inicio_supernt.php'],
			['Modulo de Gestion Central','inicio_supercentral.php'],
			['Modulo de Gestion Regional','inicio_supernt.php'],
			['Modulo de Gestion Operativo','inicio_superoperativo.php'],
			['Modulo de Gestion Administracion','inicio_superadministrador.php'],
		],
	];